### ISSUE TITLE
User can be quized on flash cards

### ISSUE THREAD

**Issue by MouseZero** [MouseZero/flash-cards#3]
- [x] Create a QuizCard component that shows a question.
- [x] Enhance QuizCard component to include a button to reveal the answer.
- [x] Add an API endpoint to embed `attempts` to answer a Question in a FlashCard.
  - Record time answered.
  - FlashCard id.
  - `wrong | ok | easy | hard` 
- [x] Enhance QuizCard component to include buttons
- [x] send attempt status to the API.
- [x] define what a `cards` object looks like in the README
- [x] Reduce duplicate collection instantiations in API routes.
- [x] Separate files based on feature for organization

**Comment by thebearingedge** [comment]
How about "User can record success or failure for a flashcard".
- [ ] Create a QuizCard component that shows a question.
- [ ] Enhance QuizCard component to include a button to reveal the answer.
- [ ] Add an API endpoint to record success or failure to answer a Question for a FlashCard.
- [ ] Enhance QuizCard component to include buttons to send success or failure to the API.

Then the next feature can be "User can be quizzed on their FlashCard collection".

**Comment by MouseZero** [comment]
Sounds good keep it small and focused
